ioctl_cfg80211: Small adaptations for the zenfone3 advanced kernel
Fix the following compiler errors which are probably specific to
this kernel:

os_dep/linux/ioctl_cfg80211.h:

In file included from ./include/osdep_intf.h:105,
                 from ./include/drv_types.h:92,
                 from ./os_dep/linux/ioctl_cfg80211.c:17:
./os_dep/linux/ioctl_cfg80211.c: In function ‘rtw_cfg80211_indicate_disconnect’:
./include/../os_dep/linux/ioctl_cfg80211.h:392:85: error: too few arguments to function ‘cfg80211_disconnected’
  392 | #define rtw_cfg80211_disconnected(wdev, reason, ie, ie_len, locally_generated, gfp) cfg80211_disconnected(wdev_to_ndev(wdev), reason, ie, ie_len, gfp)
      |                                                                                     ^~~~~~~~~~~~~~~~~~~~~
./os_dep/linux/ioctl_cfg80211.c:1215:4: note: in expansion of macro ‘rtw_cfg80211_disconnected’
 1215 |    rtw_cfg80211_disconnected(pwdev, reason, NULL, 0, locally_generated, GFP_ATOMIC);
      |    ^~~~~~~~~~~~~~~~~~~~~~~~~
In file included from ./include/osdep_service_linux.h:98,
                 from ./include/osdep_service.h:55,
                 from ./include/drv_types.h:26,
                 from ./os_dep/linux/ioctl_cfg80211.c:17:
../include/net/cfg80211.h:4862:6: note: declared here
 4862 | void cfg80211_disconnected(struct net_device *dev, u16 reason,
      |      ^~~~~~~~~~~~~~~~~~~~~

os_dep/linux/ioctl_cfg80211.c:

./os_dep/linux/ioctl_cfg80211.c:9830:17: error: initialization of ‘int (*)(struct wiphy *, struct net_device *, struct station_del_parameters *)’ from incompatible pointer type ‘int (*)(struct wiphy *, struct net_device *, const u8 *)’ {aka ‘int (*)(struct wiphy *, struct net_device *, const unsigned char *)’} [-Werror=incompatible-pointer-types]
 9830 |  .del_station = cfg80211_rtw_del_station,
      |                 ^~~~~~~~~~~~~~~~~~~~~~~~
./os_dep/linux/ioctl_cfg80211.c:9830:17: note: (near initialization for ‘rtw_cfg80211_ops.del_station’)

Signed-off-by: Planet-X <planetx.dev@gmail.com>