ioctl_cfg80211: Don't initialize set_monitor_channel of rtw_cfg80211_ops twice
Introduced by commit aaef1baf310fe0a452a00f7ae20fe6bc79c47b7a.

This fixes the following gcc error:
os_dep/linux/ioctl_cfg80211.c:9512:25: error: initialized field overwritten [-Werror=override-init]
 9512 |  .set_monitor_channel = cfg80211_rtw_set_monitor_channel,

Signed-off-by: Planet-X <planetx.dev@gmail.com>