os_dep: rtw_android: Fix return value of wifi_get_country_code()
This actually never returned any country code as the condition
always evaluated to false due to the comma operand.
Remove it to fix this behaviour.

The issue was identified by gcc-10 via the following error:

./os_dep/linux/rtw_android.c: In function ‘wifi_get_country_code’:
./os_dep/linux/rtw_android.c:1086:62: error: left-hand operand of comma expression has no effect [-Werror=unused-value]
 1086 |  if (wifi_control_data && wifi_control_data->get_country_code, 0)
      |                                                              ^

Signed-off-by: Planet-X <planetx.dev@gmail.com>